---
deployment:
  tasks:
    - export DEPLOYPATH=/home/prit8692/public_html/fairuzmk.my.id
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R aplikasi $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH